#include <iostream>
#include <random>
#include <vector>
#include <algorithm>
#include <numeric>

//include = import 
//io in out, stream flujo de entrada y salida 

//juez playmobil azul
void darBienvenida()
//void es q no me va a regresar nada 
{
    std::cout<<"Bienvenidos y bienvenidas al torneo internacional de clavados 2025 ";
    //cout es un print
}


float gen_weighted_num(){
    /*gens weighted nums*/
    std::random_device rd; 
    std::mt19937 gen(rd()); //randomizer, from library 

    std::discrete_distribution<> weighted_choice({5,10,15,30,20,15,5}); //is like generating an array and saying how much data is goin in each bin 

    //how are my bins filled, assigns it a number, based on my weights above

    int choice= weighted_choice(gen);
    std::uniform_real_distribution<>dist1(1.4,1.9); 
    std::uniform_real_distribution<>dist2(2,2.5);
    std::uniform_real_distribution<>dist3(2.5,3);
    std::uniform_real_distribution<>dist4(3,3.5);
    std::uniform_real_distribution<>dist5(3.5,4); 
    std::uniform_real_distribution<>dist6(4,4.5);
    std::uniform_real_distribution<>dist7(4.5,5);
    //uses the function choice to pick a distribution based on weights, pick a num from 0-6, thats why its an integer
    float result; 
    
    switch (choice){
        case 0: result= dist1(gen);break;
        case 1: result= dist2(gen);break;
        case 2: result= dist3(gen);break; 
        case 3: result= dist4(gen);break; 
        case 4: result= dist5(gen);break;
        case 5: result= dist6(gen);break;
        default: result = dist7(gen);break; 

    }
    return result; 
    //runs the random module, based on the "bin" it picked w the weights
}

class judge_score_gen {
public: 
    std::discrete_distribution<> weighted_choice;

    judge_score_gen(std::initializer_list<double> weights)
        : weighted_choice(weights) {}

    float generate() {
        std::random_device rd; 
        std::mt19937 gen(rd());

        int choice = weighted_choice(gen);

        std::uniform_real_distribution<> dist1(0,2); 
        std::uniform_real_distribution<> dist2(2,4);
        std::uniform_real_distribution<> dist3(4,5.5);
        std::uniform_real_distribution<> dist4(5.5,6.5);
        std::uniform_real_distribution<> dist5(6.5,8.5); 
        std::uniform_real_distribution<> dist6(8.5,9);
        std::uniform_real_distribution<> dist7(9,10);

        float result; 
        
        switch (choice){
            case 0: result= dist1(gen);break;
            case 1: result= dist2(gen);break;
            case 2: result= dist3(gen);break; 
            case 3: result= dist4(gen);break; 
            case 4: result= dist5(gen);break;
            case 5: result= dist6(gen);break;
            default: result = dist7(gen);break; 
        }

        return result;
    }
};

float judge_score_1(){
    judge_score_gen generator({5,17,20,30,15,8,5});
    return generator.generate();

}

float judge_score_2(){
    judge_score_gen generator({5,8,15,25,25,17,5});
    return generator.generate();
   
}

float judge_score_3(){
    judge_score_gen generator({5,8,15,20,30,17,5}); 
    return generator.generate();
   
}

float judge_score_4(){
    judge_score_gen generator({5,8,17,20,30,15,5});
    return generator.generate();
}

float judge_score_5(){ 
    judge_score_gen generator({5,8,17,20,30,15,5});
    return generator.generate();
}

float judge_score_6(){ 
    judge_score_gen generator({5,8,17,20,30,15,5});
    return generator.generate();
}

float judge_score_7(){ 
    judge_score_gen generator({5,8,17,20,30,15,5});
    return generator.generate();
}


int main()
//int es q me va a decir q tipo de dato me va a regresar
//es para definir funciones, las llaves es para decir donde inicia mi instruccion y donde acaba
{
    darBienvenida(); 
    
    //clavadista 1
    std::string clavadista_1="Alejandro Orozco";
    std::string pais_1="Mexico";
    //esto solo esta generando una variable
    //libreria standard de c++, es como declarar q algo esta en una libreria

    std::vector<float> final_scores_1;   // store final dive scores
    float total_final_1 = 0;

    for (int dive=0;dive<5;dive++){
        float dificultad = gen_weighted_num();
        /*now whatd need 2 do its to make my arrays for 5 dives per diver and 7 scores per dive
        need 2 to dives_dif[] that appends each dive inside a for in range 5 and inside that a for in range 7 
        and make the array score_dive_n[], and append each score generated by the ifs below, so you can do 
        the min max thing */
        std::vector<float> judge_scores;
        //initialize vector to append my scores 
  
        for (int judge=0;judge<7;judge++){
            float judge_1_score;

            if (dificultad >= 1.4 && dificultad < 1.9){
                judge_1_score=judge_score_1();
            }
            else if (dificultad> 1.9 && dificultad <2.4){
                judge_1_score=judge_score_2();
            }
            else if (dificultad>2.4 && dificultad<3.0){
                judge_1_score=judge_score_3();
            }
            else if (dificultad>3.0 && dificultad<3.5){
                judge_1_score=judge_score_4();
            }
            else if (dificultad>3.5 && dificultad<4.0){
                judge_1_score=judge_score_5();
            }
            else if (dificultad>4.0 && dificultad<4.5){
                judge_1_score=judge_score_6();
            }
            else {
                judge_1_score=judge_score_7();
            }
        
            judge_scores.push_back(judge_1_score);
        }

        float min_score=*std::min_element(judge_scores.begin(),judge_scores.end());
        float max_score=*std::max_element(judge_scores.begin(),judge_scores.end());
        float sum_scores= std::accumulate(judge_scores.begin(),judge_scores.end(),0.0f);
        float total_score=sum_scores - min_score - max_score;
        float final_dive_score= total_score * dificultad;

        final_scores_1.push_back(final_dive_score); //appendea
        total_final_1 += final_dive_score;
    }


    //otro clavadista 
    std::string clavadista_2="ALejandra Apellido";
    std::string pais_2="Mexico";

    std::vector<float> final_scores_2;   
    float total_final_2 = 0;

    for (int dive=0;dive<5;dive++){
        float dificultad = gen_weighted_num();
        std::vector<float> judge_scores;

        for (int judge=0;judge<7;judge++){
            float judge_1_score;

            if (dificultad >= 1.4 && dificultad < 1.9){
                judge_1_score=judge_score_1();
            }
            else if (dificultad> 1.9 && dificultad <2.4){
                judge_1_score=judge_score_2();
            }
            else if (dificultad>2.4 && dificultad<3.0){
                judge_1_score=judge_score_3();
            }
            else if (dificultad>3.0 && dificultad<3.5){
                judge_1_score=judge_score_4();
            }
            else if (dificultad>3.5 && dificultad<4.0){
                judge_1_score=judge_score_5();
            }
            else if (dificultad>4.0 && dificultad<4.5){
                judge_1_score=judge_score_6();
            }
            else {
                judge_1_score=judge_score_7();
            }

            judge_scores.push_back(judge_1_score);
        }

        float min_score=*std::min_element(judge_scores.begin(),judge_scores.end());
        float max_score=*std::max_element(judge_scores.begin(),judge_scores.end());
        float sum_scores= std::accumulate(judge_scores.begin(),judge_scores.end(),0.0f);
        float total_score=sum_scores - min_score - max_score;
        float final_dive_score= total_score * dificultad;

        final_scores_2.push_back(final_dive_score); //appendea enn la matriz
        total_final_2 += final_dive_score;
    }

    //usa como nn ciclo for para printear mi matriz

    std::cout << "\n\nRESULTADOS FINALES:\n";

    std::cout << "\n" << clavadista_1 << " (" << pais_1 << ")\n";
    for (int i=0;i<final_scores_1.size();i++){
        std::cout << "Clavado " << i+1 << ": " << final_scores_1[i] << "\n";
    }
    std::cout << "TOTAL FINAL: " << total_final_1 << "\n";


    std::cout << "\n" << clavadista_2 << " (" << pais_2 << ")\n";
    for (int i=0;i<final_scores_2.size();i++){
        std::cout << "Clavado " << i+1 << ": " << final_scores_2[i] << "\n";
    }
    std::cout << "TOTAL FINAL: " << total_final_2 << "\n";


    //Declara ganador
    std::cout << "\nGANADOR: ";
    if (total_final_1 > total_final_2)
        std::cout << clavadista_1 << "\n";
    else if (total_final_2 > total_final_1)
        std::cout << clavadista_2 << "\n";
    else
        std::cout << "EMPATE\n";

    return 0;
}
